loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.DetalhePerfil.as_view(), name='detalheperfil'),

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('criarusuario/', views.CriarUsuario.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('deletarusuario/', views.DeletarUsuário.as_view(), name='deletar_usuario'),
    
    path('updateuserinfo/', views.updateUserInfo , name="update_user_info"),
    path('updateuseradress/', views.updateUserAdress, name="update_user_adress"),
    path('updatePassword/', views.updatePassword, name="update_password"),
    path('atualizarsenha/', views.AtualizarSenha.as_view(), name='atualizarsenha'),
]

produto/urls.py
"""
    App produto

    Este app é o app que guarda as funcionalidades voltadas para manipulação de produtos
    no nosso e-comerce. Aqui é onde se detalha, se adiciona ao carrinho de compras etc.

    As funcionalidades desse app são listadas abaixo:

    1. Na url '', é a url principal da nossa aplicação, é nela que veremos todos os produtos
    presentes na nossa base de dados. Os produtos são listados em forma de carts simples, com foto
    nome e uma pequena descrição.

    2. Na url '<slug>', expomos os detalhes a cerca do produto escolhido na página principal,
    seu nome e sua descrição, se há variações e se o preço de cada variação.

    3. Na url 'adicionaraocarrinho/', é possivel adicionar o produto selecionado/detalhado ao carrinho
    de compras. para que possamos depois manipular nosso pedido.

    4. Na url 'removerdocarrinho/', é possivel removermos algum produto do nosso carrinho antes de termi-
    nármos o pedido.

    5. Na url 'carrinho/', é possível vermos como se encontra atualmente nosso carrinho de compras.

    6. Na url 'resumodacompra/', podemos finalmente ver o resumo da nossa compra, como preço final, já
    com adicionais de frete, descontos de cupom, dentre outros.

"""


from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('comprar/', views.Comprar.as_view(), name='comprar'),
    path('comentar/', views.adicionarComentario, name="comentar"),
]

perfil/forms.py
from django import forms
from utils.validacpf import valida_cpf
from . import models
from django.contrib.auth.models import User

class PerfilForm(forms.ModelForm):
    class Meta:
        # model que será usado para criar o formulário
        model = models.Perfil
        # fields: Campos do model que serão incluídos no formulário, nesse caso '__all__'
        # indica que todos os campos serão incluídos no formulário
        fields = '__all__'
        # exclude: Campos que serão excluídos do formulário que iremos criar, nesse caso,
        # somente o campo 'username'
        exclude = ('usuario',)


class UserForm(forms.ModelForm):
    # O atributo abaixo faz com que não exibamos no formulário, se o usuário estiver logado
    # sua senha cadastrada no sistema, mas sim, um campo de senha padrão. As configurações
    # também incluem que, para a renovação do cadastro, o campo de senha não seja

    def __init__(self, usuario=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Se o usuário estiver logado, saberemos que usuário enviou este formulário
        self.usuario = usuario

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_messages = {}

        user_data = cleaned.get('username')                     # Usuário da aplicação
        email_data = cleaned.get('email')                       # Email da aplicação

        user_db = User.objects.filter(username=user_data).first() # Usuário do banco de dados
        email_db = User.objects.filter(email=email_data).first()  # Email do banco de dados

        # Configuração das mensagens de erro
        error_msg_user_exists = 'Usuário já existe.'
        error_msg_email_exists = 'E-mail já existe.'
    

        # Se existirem erros de validação na hora do cadastro de usuário
        if validation_error_messages:
            raise(forms.ValidationError(
                validation_error_messages
            ))

class PasswordForm(forms.ModelForm):
        
    # Senha
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Senha'
    )
    # Confirmação da senha
    password_confirm = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Confirmar Senha'
    )

    class Meta:
        model = User
        fields = (
            'password',
            'password_confirm',
        )

    def __init__(self, usuario=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Se o usuário estiver logado, saberemos que usuário enviou este formulário
        self.usuario = usuario

    def clean(self, *args, **kwargs):

        data = self.data
        validation_error_messages = {}

        # Mensagens de erro
        error_msg_password_short = 'A senha digitada precisa ser igual ou maior que 6 caracteres.'
        error_msg_required_field = 'Este campo é obrigatório.'
        error_msg_password_not_match = 'As senhas digitadas não são iguais.'

        password_data = data.get('password')  # Senha da aplicação
        password_confirm_data = data.get('password_confirm')  # Senha de confirmação da aplicação

        if not password_data:
            validation_error_messages['password'] = error_msg_required_field
        
        if not password_confirm_data:
            validation_error_messages['password_confirm'] = error_msg_required_field

        # Verificação de senhas
        if len(password_data) < 6:
            validation_error_messages['password'] = error_msg_password_short

        if password_data != password_confirm_data:
            validation_error_messages['password_confirm'] = error_msg_password_not_match

        # Se houver mensagens de erro, mostra no formulário
        if validation_error_messages:
            raise(forms.ValidationError(
                validation_error_messages
            ))

perfil/views.py
from utils.utils import valida_cpf, calcula_idade, formata_data
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib import messages
from django.views import View
from datetime import datetime
from . import models, forms
import string
import copy
import re

# Cria usuário django com username, first_name, last_name, email, password
class CriarUsuario(View):

    template_name = 'perfil/cadastro_ou_pagprincipal.html'

    def post(self, *args, **kwargs):

        novo_usuario = self.request.POST.get('newuser')
        email = self.request.POST.get('email')
        senha = self.request.POST.get('pswd')
        self.carrinho = copy.deepcopy(self.request.session.get('carrinho'), {})
        self.request.session.save()

        # Verificar se o usuário já está cadastrado
        if User.objects.filter(username=novo_usuario):
            messages.error(
                self.request,
                'Usuário já existe'
            )
            return render(self.request, self.template_name)
        
        # Verificar se o email já está cadastrado
        if User.objects.filter(email=email):
            messages.error(
                self.request,
                'Email já existe'
            )
            return render(self.request, self.template_name)

        # Criando novo usuário django
        user = User.objects.create_user(username=novo_usuario,
                                        email=email,
                                        password=senha)
        # Login
        autentica = authenticate(
            self.request,
            username=novo_usuario,
            password=senha
        )
        if autentica:
            login(
                self.request,
                autentica
            )
        return render(self.request, self.template_name)

# Faz login do usuário djnago depois de criado
class Login(View):
    """
        Autentica e faz login
    """

    template_login="perfil/login-signup.html"
    def get(self, *args, **kwargs):
        return render(self.request, self.template_login)


    def post(self, *args, **kwargs):
        usuario = self.request.POST.get('usuario')
        senha = self.request.POST.get('senha')

        if not usuario or not senha:
            messages.error(self.request,'Usuário ou Senha incorretos.')
            return render(self.request, self.template_login)

        autentica = authenticate(self.request, username=usuario, password=senha)
        if autentica:
            login(self.request, autentica)
            messages.success(self.request,'Login efetuado com sucesso')
            return redirect('produto:lista')
        else:
            messages.error(self.request,'Usuário ou senha inválidos')
            return render(self.request, self.template_login)

# Faz logout do usuário django quando termina a seção
class Logout(View):
    """
        Faz logout e salva o carrinho de compras.
    """
    def get(self, *args, **kwargs):
        carrinho = copy.deepcopy(self.request.session.get('carrinho'))
        self.request.session['carrinho'] = carrinho
        self.request.session.save()  # Salvando carrinho na sessão para que não perdamos ele ao fazer
        # logout
        logout(self.request)
        return redirect('produto:lista')

# Atualiza dados de perfil/cadastro de usuário
class Atualizar(View):
    """
        Atualizar dados de usuário/perfil.
    """
    def __init__(self) -> None:        
        self.template_name = "perfil/atualizar.html"
        self.template_name_test = "perfil/detalhe-perfil.html"
        self.contexto = {}


    def get(self, *args, **kwargs):
        """
            Resgata da base de dados e carrega os dados do usuário e do perfil no formulario.
            Se não houver dados no perfil, só será carregados dados de usuário.        """
        perfil = models.Perfil.objects.filter(usuario = self.request.user).first()
        if perfil:
                self.contexto = {
                    'user': User.objects.get(username=self.request.user),
                    'perfil': perfil
                }
        else:
            self.contexto = {
            'userform': forms.UserForm(
                data=self.request.POST or None,
                usuario=self.request.user,
                instance=self.request.user
            ),
            'perfilform': forms.PerfilForm()
        }


        return render(self.request, self.template_name_test, self.contexto)


    # def post(self, *args, **kwargs):
    #     """
    #         Resgada os dados dos formulario de Usuário e de Perfil e salva na base de dados.
    #     """
    #     # Atualizando dados de usuário. 
    #     user = User.objects.get(username = self.request.user)        
    #     perfil = models.Perfil.objects.filter(usuario = self.request.user).first()
        
    #     if perfil:
    #             self.contexto = {
    #                 'userform': forms.UserForm(
    #                     data=self.request.POST or None,
    #                     usuario=self.request.user,
    #                     instance=self.request.user
    #                 ),
    #                 'perfilform': forms.PerfilForm(
    #                     instance=perfil
    #                 )
    #             }
    #     else:
    #         self.contexto = {
    #         'userform': forms.UserForm(
    #             data=self.request.POST or None,
    #             usuario=self.request.user,
    #             instance=self.request.user
    #         ),
    #         'perfilform': forms.PerfilForm()
    #     }

    #     # Resgatando dados do formulario de usuário
    #     usuario = self.request.POST.get('username')
    #     email = self.request.POST.get('email')
    #     nome = self.request.POST.get('first_name')
    #     sobrenome = self.request.POST.get('last_name')

    #     # Salvando dados de usuário no banco de dados
    #     # Verficação da existencia do usuário no banco de dados
    #     query_user = User.objects.get(username = usuario)
    #     if usuario != user.username and query_user:
               
    #         messages.error(
    #             self.request,
    #             'Usuário já existe'
    #         )
    #         return render(
    #             self.request,
    #             template_name=self.template_name,
    #             context=self.contexto
    #         )
    #     else:
    #         # salvar novo username e relogar o usuário
    #         pass

    #     user.email = email
    #     user.first_name = nome
    #     user.last_name = sobrenome
    #     user.save()
        
    #     ## Salvando dados de perfil ##

    #     # Resgatando dados do formulario
    #     bairro = self.request.POST.get('bairro')
    #     cep = self.request.POST.get('cep')
    #     cidade = self.request.POST.get('cidade')
    #     complemento = self.request.POST.get('complemento')
    #     cpf = self.request.POST.get('cpf')
    #     data_nascimento = self.request.POST.get('data_nascimento')
    #     endereco = self.request.POST.get('endereco')
    #     estado = self.request.POST.get('estado')
    #     idade = self.request.POST.get('idade')
    #     numero = self.request.POST.get('numero')
        
    #     # Verificações de integridade dos dados
    #     if not valida_cpf(cpf):
    #         messages.error(self.request,'CPF inválido')
    #         return render(self.request, self.template_name, self.contexto)

    #     idade_log = calcula_idade(datetime.strptime(data_nascimento, "%d/%m/%Y").date())
    #     if int(idade) != idade_log:
    #         idade = idade_log

    #     if len(cep) < 8:
    #         messages.error(self.request, 'CEP inválido')
    #         return render(self.request, self.template_name, self.contexto)
        
    #     if datetime.strptime(data_nascimento, "%d/%m/%Y") > datetime.today():
    #         messages.error(self.request, 'Data de Nascimento não pode ser maior do que data atual.')
    #         return render(self.request, self.template_name, self.contexto)
  
    #     # fim das verificações

    #     if perfil:
    #         # Salvar dados do formulario de perfil no banco de dados
    #         perfil.data_nascimento = formata_data(data_nascimento)
    #         perfil.complemento = complemento
    #         perfil.endereco = endereco
    #         perfil.cidade = cidade
    #         perfil.bairro = bairro
    #         perfil.estado = estado
    #         perfil.numero = numero
    #         perfil.usuario = user
    #         perfil.idade = idade
    #         perfil.cep = cep
    #         perfil.cpf = cpf
    #     else:
    #         perfil = models.Perfil(
    #             data_nascimento = formata_data(data_nascimento),
    #             complemento = complemento,
    #             endereco = endereco,
    #             cidade = cidade,
    #             bairro = bairro,
    #             estado = estado,
    #             numero = numero,
    #             usuario = user,
    #             idade =idade,
    #             cep = cep,
    #             cpf = cpf
    #         )

    #     perfil.save()        

    #     messages.success(self.request, 'Usuário salvo com sucesso')
    #     return redirect( 'produto:lista')

# Mostra os detalhes do perfil no template
class DetalhePerfil(ListView):
    """
        Detalha os dados do perfil do usuário
    """
    model = models.Perfil
    template_name = 'perfil/detalhe.html'
    context_object_name = 'perfil'

# Deleta usuário da base de dados
class DeletarUsuário(View):
    """
        Esta view deleta o usuário logado.
    """

    @login_required(redirect_field_name='login')
    def get(self, *args, **kwargs):

        if self.request.user.is_authenticated:

perfil/templates/perfil/cadastro_ou_pagprincipal.html
{% extends 'base.html' %}


{% block content %}
<!-- Pergunta: Continuar cadastro ou Seguir para Página Principal -->
<div class="row d-flex justify-content-center" style="width: 100%;">
    <div class="b-main-container">
        <h2>Qual será seu próximo passo?</h2> <br> <br>
        <div class="b-container">
            <!-- Terminar cadastro de usuário -->
            <a href="{% url 'perfil:atualizar' %}" class="b-link">
                <button class="butom-loger">Termine seu cadastro</button>
            </a>
            <!-- Ir para Página Inicial -->
            <a href="{% url 'produto:lista' %}" class="b-link">
                <button class="butom-loger">Página Principal</button>
            </a>
            
        </div>
    </div>
</div>

{% endblock %}

perfil/templates/perfil/detalhe-perfil.html
{% extends 'base.html' %}
{% load omfilters %}


{% block content %} 

<div class="box">
    <div class="menu">
        
        <div class="card-user">
            <!-- IMAGEM DO CARD -->
            <div class="image-card-user">
                <img src="https://cdn-icons-png.flaticon.com/512/6073/6073873.png" alt="Imagem de usuário vazio">
            </div>
            
            <div  class="info-card-user">
                <h6>{{user.username}}</h6>
                <div class="icons-card-user">
                <!-- ICONE DE EDITAR PERFIL -->
                <a href="">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                    </svg>
                </a>
                <!-- ICONE DE EXCLUIR PERFIL -->
                <a href="">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-x" viewBox="0 0 16 16">
                        <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                        <path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                    </svg>
                </a>
                </div>
            </div>
        </div>
        <!-- Colaose Menu da barra lateral esqueda da página -->
        <div class="links-user">
            
            <details>                      
                <summary>Minha Conta</summary>
                <ul>
                    <a href="#form-user-id"><li>Perfil</li></a>
                    <a href="#"><li>Cartões / Contas Bancárias</li></a>
                    <a href="#form-adress-id"><li>Endereço</li></a>
                    <a href="#form-password-change">Mudar Senha</a>
                </ul>
            </details>
        </div>

    </div>
    <div class="info">

        <div class="forms-info">
            <!-- Formulario de Informações do usuário -->
            <div class="form-user" id="form-user-id">
                <h3 class="mb-4">Informações de Usuário</h3>
                <form action="{% url 'perfil:update_user_info' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Primeiro Nome: </span>
                        <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user.first_name }}"aria-describedby="basic-addon3" placeholder="Digite seu primeiro nome" required>
                    </div>

                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Sobrenome: </span>
                        <input type="text" class="form-control" id="last_name" name="last_name" value="{{ user.last_name}}" aria-describedby="basic-addon3" placeholder="Digite seu sobrenome" required>
                    </div>
                    
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Data de Nascimento: </span>
                        <input type="date" class="form-control" id="data_nascimento" name="data_nascimento" value="{{perfil.data_nascimento}}" aria-describedby="basic-addon3" placeholder="Digite sua data de nascimento" required>
                    </div>
                    
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">CPF: </span>
                        <input type="text" class="form-control" id="cpf" name="cpf" value="{{perfil.cpf}}" aria-describedby="basic-addon3" placeholder="Digite seu CPF" maxlength="11" required>
                    </div>

                    <div class="row d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary px-4 mx-3">Guardar</button>
                    </div>
                </form>
            </div>

            <!-- Formulario de Endereço -->
            <div class="form-user" id="form-adress-id">
                <h3 class="mb-4">Informações de Endereço</h3>
                <form action="{% url 'perfil:update_user_adress' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Rua: </span>
                        <input type="text" class="form-control" id="rua" name="rua" value="" aria-describedby="basic-addon3" placeholder="Digite o nome da sua rua" required>
                    </div>
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Bairro: </span>
                        <input type="text" class="form-control" id="bairro" name="bairro" value="" aria-describedby="basic-addon3" placeholder="Digite o seu bairro" required>
                    </div>
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Numero: </span>
                        <input type="text" class="form-control" id="numero" name="numero" value="" aria-describedby="basic-addon3" placeholder="Digite o numero da sua casa" required>
                    </div>
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Cidade: </span>
                        <input type="text" class="form-control" id="cidade" name="cidade" value="" aria-describedby="basic-addon3" placeholder="Digite sua cidade" required>
                    </div>
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">CEP: </span>
                        <input type="text" class="form-control" id="cep" name="cep" value="" aria-describedby="basic-addon3" placeholder="Digite o seu CEP" required>
                    </div>
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Complemento: </span>
                        <input type="text" class="form-control" id="complemento" name="complemento" value="" aria-describedby="basic-addon3" placeholder="" required>
                    </div>

                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Estado: </span>
                        <select name="select-estado" id="select" class="form-select">
                            <option value="AC">Acre</option>
                            <option value="AL">Alagoas</option>
                            <option value="AP">Amapá</option>
                            <option value="AM">Amazonas</option>
                            <option value="BA">Bahia</option>
                            <option value="CE">Ceará</option>
                            <option value="DF">Distrito Federal</option>
                            <option value="ES">Espirito Santo</option>
                            <option value="GO">Goiás</option>
                            <option value="MA">Maranhão</option>
                            <option value="MT">Mato Grosso</option>
                            <option value="MS">Mato Grosso do Sul</option>
                            <option value="MG">Minas Gerais</option>
                            <option value="PA">Pará</option>
                            <option value="PB">Paraiba</option>
                            <option value="PR">Paraná</option>
                            <option value="PE">Pernambuco</option>
                            <option value="PI">Paiuí</option>
                            <option value="RJ">Rio de Janeiro</option>
                            <option value="RN">Rio Grande do Norte</option>
                            <option value="RS">Rio Grande do Sul</option>
                            <option value="RO">Rondonia</option>
                            <option value="RR">Roraima</option>
                            <option value="SC">Santa Catarina</option>
                            <option value="SP">São Paulo</option>
                            <option value="SE">Sergipe</option>
                            <option value="TO">Tocantins</option>
                        </select>
                    </div>
                    
                    <div class="row d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary px-4 mx-3">Guardar Endereço</button>
                    </div>

                </form>
            </div>

            <!-- Formulário para Troca de Senha -->
            <div class="form-user" id="form-password-change">
                <h3 class="mb-4">Trocar Senha</h3>
                <form action="{% url 'perfil:update_password' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Senha Antiga: </span>
                        <input type="password" class="form-control" id="old_password" name="old_password" value="" aria-describedby="basic-addon3" placeholder="" required>
                    </div>
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Nova Senha: </span>
                        <input type="password" class="form-control" id="new_password" name="new_password" value="" aria-describedby="basic-addon3" placeholder="" required>
                    </div>
                    <div class="input-group mb-2">
                        <span class="input-group-text" id="basic-addon3" style="min-width: 180px;">Senha Antiga: </span>
                        <input type="password" class="form-control" id="new_password_confirm" name="new_password_confirm" value="" aria-describedby="basic-addon3" placeholder="" required>
                    </div>

                    <div class="row d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary px-4 mx-3">Mudar senha</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

perfil/templates/perfil/login-signup.html
{% extends 'base.html' %}

{% block content %}
<!-- Conteudo -->
<div class="row d-flex justify-content-center" style="width: 100%;">

    <div class="container-login">
    <div class="main-login">  	
        <input type="checkbox" id="chk" aria-hidden="true">
    
            <div class="signup">
                <form method="POST" action="{% url 'perfil:criar' %}">
                    {% csrf_token %}
                    <label class="label-login" for="chk" aria-hidden="true">Inscrever-se</label>
                    <input class="input-login" type="text" name="newuser" placeholder="Usuário" required="">
                    <input class="input-login" type="email" name="email" placeholder="Email" required="">
                    <input class="input-login" type="password" name="pswd" placeholder="Senha" required="">
                    <button type="submit" class="button-login">Inscrever-se</button>
                </form>
            </div>
    
            <div class="login">
                <form method="POST" action="{% url 'perfil:login' %}">
                    {% csrf_token %}
                    <label class="label-login" for="chk" aria-hidden="true">Entrar</label>
                    <input
                            class="input-login"
                            id="usuario"
                            name="usuario"
                            type="text"
                            name="user"
                            placeholder="Usuário"
                            required="">
    
                    <input
                            class="input-login"
                            id="senha"
                            name="senha"
                            type="password"
                            placeholder="Senha"
                            required="">
                    <button type="submit" class="button-login">Entrar</button>
                </form>
            </div>
    </div>
    </div>
</div>

{% endblock %}