loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.DetalhePerfil.as_view(), name='detalheperfil'),

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('criarusuario/', views.CriarUsuario.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('deletarusuario/', views.DeletarUsuário.as_view(), name='deletar_usuario'),
    
    path('updateuserinfo/', views.updateUserInfo , name="update_user_info"),
    path('updateuseradress/', views.updateUserAdress, name="update_user_adress"),
    path('updatePassword/', views.updatePassword, name="update_password"),
    path('atualizarsenha/', views.AtualizarSenha.as_view(), name='atualizarsenha'),
]

produto/urls.py
"""
    App produto

    Este app é o app que guarda as funcionalidades voltadas para manipulação de produtos
    no nosso e-comerce. Aqui é onde se detalha, se adiciona ao carrinho de compras etc.

    As funcionalidades desse app são listadas abaixo:

    1. Na url '', é a url principal da nossa aplicação, é nela que veremos todos os produtos
    presentes na nossa base de dados. Os produtos são listados em forma de carts simples, com foto
    nome e uma pequena descrição.

    2. Na url '<slug>', expomos os detalhes a cerca do produto escolhido na página principal,
    seu nome e sua descrição, se há variações e se o preço de cada variação.

    3. Na url 'adicionaraocarrinho/', é possivel adicionar o produto selecionado/detalhado ao carrinho
    de compras. para que possamos depois manipular nosso pedido.

    4. Na url 'removerdocarrinho/', é possivel removermos algum produto do nosso carrinho antes de termi-
    nármos o pedido.

    5. Na url 'carrinho/', é possível vermos como se encontra atualmente nosso carrinho de compras.

    6. Na url 'resumodacompra/', podemos finalmente ver o resumo da nossa compra, como preço final, já
    com adicionais de frete, descontos de cupom, dentre outros.

"""


from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('comprar/', views.Comprar.as_view(), name='comprar'),
    path('comentar/', views.adicionarComentario, name="comentar"),
]

templates/parciais/_carrinho.html
{% load omfilters %}
{% load static %}

<div class="table-responsive">

    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>
        <!-- Loop sobre as linhas/produtos que existem no carrinho -->
        {% for linha in request.session.carrinho.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
            </td>
            <td>
                <a href="{% url 'produto:detalhe' linha.slug %}">
                    {{ linha.produto_nome }}
                </a>
                <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                    </svg>
                </a>
            </td>
            <td>
                {{ linha.variacao_nome }}
            </td>

            <td>
                <!-- Quantidade de cada produto/varição exibida no carrinho -->
                {{ linha.quantidade }}x

                <!-- Se existir preço promocional, exibe os valores que estão em preço -->
                <!-- unitário promocional-->
                {% if linha.preco_unitario_promocional %}
                {{ linha.preco_unitario_promocional }}
                {% else %}
                {{ linha.preco_unitario }}
                {% endif %}
            </td>
            <!--Exibe valor final-->
            {% if linha.preco_quantitativo_promocional %}
            <td>{{ linha.preco_quantitativo_promocional|formata_preco }}</td>
            {% else %}
            <td>{{ linha.preco_quantitativo|formata_preco }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>


</div>

templates/parciais/_carrossel.html
{% load static %}

<div
      style="
      min-width: 100vw;
      display: flex; 
      justify-content: center;">

  <div id="carouselExampleIndicators" 
  class="carousel slide" 
  data-ride="carousel"
  style="min-height: 50vh;
         min-width: 50vw; ">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active" style="display:flex; justify-content:center;">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="https://www.shutterstock.com/image-vector/wholesale-package-logistics-outline-icon-260nw-1833259351.jpg" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
      <div class="carousel-item" style="display:flex; justify-content:center;">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-muKoaU4sY46uqUerm3TuVPnSC9B_CjKu9Fjk03__KlZ92WzSQFerbhJlMHoFCU5yPaw&usqp=CAU" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
      <div class="carousel-item" style="display:flex; justify-content:center;">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-muKoaU4sY46uqUerm3TuVPnSC9B_CjKu9Fjk03__KlZ92WzSQFerbhJlMHoFCU5yPaw&usqp=CAU" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

</div>

templates/parciais/_footer.html
{% load static %}

<style>
    .texto {
      color: #fff;
      font-weight: bold;
    }
</style>

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1 texto">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1 texto">Por Leonardo Rodrigues da Costa</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style-login.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style-loger.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style-detalhe-perfil.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load omfilters %}
{% load static %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'produto:lista' %}">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        e-comerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
              </svg>
        </button>
    </form>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">

            {% if request.session.carrinho %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'produto:carrinho' %}">
                    <span class="nav-cart-icon mr-2" style="color: white;">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                    <span class="nav-cart-text mr-1" style="color: white;">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1" style="color: white;">
                        <strong>{{ request.session.carrinho|cart_total_qtd }}x</strong>
                    </span>                    
                </a>
            </li>
            {% endif %}

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'produto:lista' %}">
                    <i class="fa fa-home" aria-hidden="true"></i>
                    Home <span class="sr-only">(current)</span></a>
            </li>

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown mr-5">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user-circle" aria-hidden="true"></i> Olá {{ request.user }}
                </a>
                <div class="dropdown-menu mr-2" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'perfil:detalheperfil' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-person" viewBox="0 0 16 16">
                            <path
                                d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                        </svg>
                        Perfil</a>
                    <a class="dropdown-item" href="{% url 'perfil:atualizar' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                        Atualize seus dados</a>
                    <a class="dropdown-item" href="{% url 'perfil:atualizarsenha' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-key" viewBox="0 0 16 16">
                                <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8zm4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5z"/>
                                <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                            </svg>
                            Mudar senha</a>
                    <a class="dropdown-item" href="{% url 'perfil:logout' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                            <path fill-rule="evenodd"
                                d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                        </svg>
                        Sair</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:login' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z" />
                        <path fill-rule="evenodd"
                            d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                    </svg>
                    Entrar</a>
            </li>
            {% endif %}


        </ul>
    </div>
</nav>