loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pedido/urls.py
"""
    App pedido.

        Neste app se concentra em características básicas de um pedido em um
    processo de compra, como por exemplo, pagar o pedido, salvar o pedido para
    pagar depois e claro, detalhar o pedido, para o cliente poder revisar e ter
    a certeza que os produtos no carrinho são mesmo o que ele quer.

        Este app tem inicialmente as três funcionalidades descritas logo acima:

    1. Na url '', é possível escolher o método de pagamento do que está no carrinho.
    2. Na url 'salvarpedido/', é possível salvar o pedido na base de dados sem perder
    o que está no carrinho.
    3. Na url 'detalhe/', é possível detalhar o que é cada produto/variação e se ter
    noção, mesmo que de maneira redundante, do que se pediu.

"""


from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.DetalhePerfil.as_view(), name='detalheperfil'),

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('criarusuario/', views.CriarUsuario.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('deletarusuario/', views.DeletarUsuário.as_view(), name='deletar_usuario'),
    
    path('updateuserinfo/', views.updateUserInfo , name="update_user_info"),
    path('updateuseradress/', views.updateUserAdress, name="update_user_adress"),
    path('updatePassword/', views.updatePassword, name="update_password"),
    path('atualizarsenha/', views.AtualizarSenha.as_view(), name='atualizarsenha'),
]

produto/urls.py
"""
    App produto

    Este app é o app que guarda as funcionalidades voltadas para manipulação de produtos
    no nosso e-comerce. Aqui é onde se detalha, se adiciona ao carrinho de compras etc.

    As funcionalidades desse app são listadas abaixo:

    1. Na url '', é a url principal da nossa aplicação, é nela que veremos todos os produtos
    presentes na nossa base de dados. Os produtos são listados em forma de carts simples, com foto
    nome e uma pequena descrição.

    2. Na url '<slug>', expomos os detalhes a cerca do produto escolhido na página principal,
    seu nome e sua descrição, se há variações e se o preço de cada variação.

    3. Na url 'adicionaraocarrinho/', é possivel adicionar o produto selecionado/detalhado ao carrinho
    de compras. para que possamos depois manipular nosso pedido.

    4. Na url 'removerdocarrinho/', é possivel removermos algum produto do nosso carrinho antes de termi-
    nármos o pedido.

    5. Na url 'carrinho/', é possível vermos como se encontra atualmente nosso carrinho de compras.

    6. Na url 'resumodacompra/', podemos finalmente ver o resumo da nossa compra, como preço final, já
    com adicionais de frete, descontos de cupom, dentre outros.

"""


from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('comprar/', views.Comprar.as_view(), name='comprar'),
    path('comentar/', views.adicionarComentario, name="comentar"),
]

produto/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from PIL import Image
import os

class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    imagem = models.ImageField(
        upload_to='produto_imagens/%Y/%m/',
        blank= True,
        null= True
    )
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(default=0, verbose_name='Preço Promo')
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variável'),
            ('S', 'Simples')
        )
    )

    def get_preco_formatado(self):
        return f'R$ {self.preco_marketing:.2f}'.replace('.', ',')
    get_preco_formatado.short_description = 'Preço'

    def get_preco_promocional_formatado(self):
        return f'R$ {self.preco_marketing_promocional:.2f}'.replace('.', ',')
    get_preco_promocional_formatado.short_description = 'Preço'

    #  Redimensionar imagem antes de salvar
    @staticmethod
    def resize_image(img, max_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name) # caminho completo da imagem
        image_pil = Image.open(img_full_path) # abrir imagem com pil
        original_width, original_height = image_pil.size # altura e largura original da imagem

        if original_width <= max_width:
            image_pil.close() # fechando a imagem aberta anteriormente
            return # se a largura original for menor que a nova largura, não precisa
                   # fazer o redimensionamento

        new_height = round((max_width * original_height) / original_width) # descobrir nova altura
        new_image = image_pil.resize((max_width, new_height), Image.LANCZOS) # redimensiona imagem
        new_image.save(         # salva a nova imagem por cima da antiga
            img_full_path,      # onde se deseja salvar a imagem
            optimize=True,
            quality=50          # reduz a qualidade para 50%
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    # Esse método define como será mostrado a representação do nosso objeto quando chamarmos
    # ele em um print
    def __str__(self):
        return self.nome

class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(
        max_length=50,
        blank=True,
        null=True
    )
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

produto/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from .models import Produto, Variacao
from perfil.models import Perfil
from comentarios.models import Comentario
import datetime


class ListaProdutos(ListView):
    """
        Lista todos os produtos da base de dados
    """
    model = Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'

# class DetalheProduto(DetailView):
#     """
#         Mostra os detalhes do produto selecionado na página principal
#     """

#     model = Produto
#     template_name = 'produto/detalhe.html'
#     context_object_name = 'produto'
#     slug_url_kwarg = 'slug'

class DetalheProduto(View):
    def get(self, *args, **kwargs):
        template_name = 'produto/detalhe.html'
        slug = kwargs['slug']

        produto = Produto.objects.filter(slug=slug).first()
        comentario_produto = Comentario.objects.filter(produto_comentario=produto).order_by('-data_comentario')

        contexto = {
            'produto': produto,
            'comentarios': comentario_produto
        }

        return render(
            self.request,
            template_name=template_name,
            context=contexto
        )

class AdicionarAoCarrinho(View):
    """
        Adiciona o produto selecionado no carrinho de compras
    """

    def get(self, *args, **kwargs):

        # HTTP_REFERER é um método que o django usa para guardar a referência da página
        # anteriormente acessada pelo usuário.
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )

        # Em produto/templates/produto/detalhes.html a tag <select> implementa o atributo
        # name="vid", que nesse caso se refere ao Id da variação do produto.
        # O método abaixo - self.request.GET.get('vid') - implementa ima forma de capturarmos
        # o id da variação do produto para podermos, posteriormente, adicioná-lo ao carrinho de
        # compras.
        variacao_id = self.request.GET.get('vid')

        # se não existir uma variação do nosso produto retornamos para página acessada
        # anteriormente
        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe'
            )
            return redirect(http_referer)

        # Captura o objeto que representa a variação na nossa base de dados
        variacao = get_object_or_404(Variacao, id=variacao_id)
        variacao_estoque = variacao.estoque
        produto = variacao.produto

        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''

        # Se o estoque for insuficiente, retornar uma mensagem de erro.
        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente.'
            )
            return redirect(http_referer)

        # Se não existir um carrinho, criamos um carrinho.
        # Uma _.session funciona como os cookies no navegador, são informações do usuário
        # sobre dados da seção, mas que serão armazenadas pelo servidor, pelo tempo que for
        # necessário.
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        # Acrescenta variação de produto ao carrinho
        carrinho = self.request.session['carrinho']
        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            # Condição para determinar se a quantidade de produtos que o usuário quer
            # adicionar no carrinho é maior que a quantidade que existe em estoque na loja.
            if variacao_estoque < quantidade_carrinho:
                messages.error(
                    self.request,
                    f'Estoque insuficiente para {quantidade_carrinho}x no produto {produto_nome}.'
                    f'Adicionamos {variacao_estoque}x no seu carrinho.'
                )
                quantidade_carrinho = variacao_estoque

            # As proximas linhas fazem o cálculo do preço dos produtos que estão no carrinho.
            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * \
                                                                      quantidade_carrinho


        else:
            carrinho[variacao_id] = {
                'produto_id':produto_id,
                'produto_nome':produto_nome,
                'variacao_nome':variacao_nome,
                'variacao_id':variacao_id,
                'preco_unitario':preco_unitario,
                'preco_unitario_promocional':preco_unitario_promocional,
                'preco_quantitativo':preco_unitario,
                'preco_quantitativo_promocional':preco_unitario_promocional,
                'quantidade': 1,
                'slug':slug,
                'imagem':imagem
            }

        # Salvando a sessão
        self.request.session.save()

        messages.success(
            self.request,
            f'Produto {produto_nome} adicionado ao seu carrinho '
            f'{carrinho[variacao_id]["quantidade"]}x.'
        )

        return redirect(http_referer)

class RemoverDoCarrinho(View):
    """
        Remove produto selecionado do carrinho de compras.
    """
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')

        # Se o ID da variação do produto não existir
        if not variacao_id:
            return redirect(http_referer)

        # Se o carrinho não existir
        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        # ...
        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)

        # Produto removido do carrinho com sucesso.
        # Mensagem antes de realmente remover o produto, porque assim
        # é possível pegar o carrinho.
        carrinho = self.request.session['carrinho'][variacao_id]
        messages.success(
            self.request,
            f'Produto {carrinho["variacao_id"]} removido do Carrinho.'
        )

        # Removendo o produto do carrinho.
        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        return redirect(http_referer)

class Carrinho(View):
    """
        Lista todos os produtos adicionados ao carrinho.
    """
    def get(self, *args, **kwargs):
        contexto = {
            'carrinho': self.request.session.get('carrinho', {})
        }
        return render(
            self.request,
            'produto/carrinho.html',
            contexto
        )

class Comprar(View):
    """
        Faz a compra de 1 produto somente
    """
    # TODO: Corrigit bug desta view. Não seleciona o produto para compra
    def get(self, *args, **kwargs):

        # HTTP_REFERER é um método que o django usa para guardar a referência da página
        # anteriormente acessada pelo usuário.
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )

        # Em produto/templates/produto/detalhes.html a tag <select> implementa o atributo
        # name="vid", que nesse caso se refere ao Id da variação do produto.
        # O método abaixo - self.request.GET.get('vid') - implementa ima forma de capturarmos
        # o id da variação do produto para podermos, posteriormente, adicioná-lo ao carrinho de
        # compras.
        print(self.request)
        variacao_id = self.request.GET.get('vid')

        # se não existir uma variação do nosso produto retornamos para página acessada
        # anteriormente
        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe'
            )
            return redirect(http_referer)

        # Captura o objeto que representa a variação na nossa base de dados
        variacao = get_object_or_404(Variacao, id=variacao_id)
        variacao_estoque = variacao.estoque
        produto = variacao.produto

        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''

        # Se o estoque for insuficiente, retornar uma mensagem de erro.
        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente.'
            )
            return redirect(http_referer)

        # Se não existir um carrinho, criamos um carrinho.
        # Uma _.session funciona como os cookies no navegador, são informações do usuário
        # sobre dados da seção, mas que serão armazenadas pelo servidor, pelo tempo que for
        # necessário.
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

produto/templates/produto/carrinho.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}
<div 
style="
    border-radius: 10px;
    margin-left: auto;
    margin-right: auto;
    background-color: white; 
    min-height: 100vh; 
    margin-top: -25px;
    padding: 10px 30px;">
    <!-- Exibe o carrinho de compras somente se existir um carrinho de compras -->
    {% if request.session.carrinho %}
    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>
            {% include 'parciais/_carrinho.html' %}
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{ request.session.carrinho|cart_totals|formata_preco }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'produto:resumodacompra' %}">
                Finalizar Compra
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:criar' %}">
                Entre para finalizar a compra
            </a>
            {% endif %}


        </div>
    </div>

    {% else %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho vazio</h3>
            <p class="lead">
                Não há produtos no seu carrinho.
            </p>
        </div>
    </div>

    {% endif %}
</div>

{% endblock %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load humanize %}
{% load omfilters %}

{% block content %}

<style>
    .detalhe {
        background-color: white;
        padding: 20px;
        border-radius: 10px;
    }
</style>

<div class="detalhe">

    <div class="row">
        <div class="col d-flex justify-content-center align-items-center" style="height: 100vh">
            <!-- Imagem do Produto -->
            {% if produto.imagem %}
            <img src="{{ produto.imagem.url }}" 
            class="img-fluid img-thumbnail" style="width: 80%; height: 80%;" alt="...">
            {% endif %}
        </div>
        <div class="col-lg">
            <div class="mt-5 mt-lg-0">
                <h3 class="mb-5 mt-5">{{ produto.nome }}</h3>

                <div class="content mb-3">
                    <p class="text-justify">
                        {{ produto.descricao_curta }}
                    </p>
                </div>

                <p class="lead">
                    {% if produto.preco_marketing_promocional %}
                        <span class="lead product-price" id="variation-preco">
                            {{ produto.preco_marketing_promocional|formata_preco }}
                        </span>
                        <span class="lead product-old-price text-muted"
                            id="variation-preco-promocional">
                            {{ produto.preco_marketing|formata_preco }}
                        </span>
                    {% else %}
                    <span class="lead product-price">
                        {{ produto.preco_marketing|formata_preco }}
                    </span>
                    {% endif %}
                </p>
                
                
                <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                
                    <div class="form-group">
                        {% if produto.variacao_set.all %}
                        <select class="form-control form-control-lg" style="width:58%" id="select-variacoes" name="vid">
                            {% for variacao in produto.variacao_set.all %}
                                {% if variacao.preco_promocional %}
                                    <option data-preco="{{ variacao.preco|formata_preco }}"
                                            data-preco-promocional="{{ variacao.preco_promocional|formata_preco }}"
                                            value="{{ variacao.id}}" style="padding: 10px;">
                                    {% if variacao.nome %}
                                        {{ variacao.nome }}
                                    {% else  %}
                                        {{ variacao  }}
                                    {% endif  %}
                                    </option>
                                {% else %}
                                    <option data-preco="{{ variacao.preco|formata_preco }}"
                                            value="{{ variacao.id}}"
                                            style="padding: 10px;">
                                    {% if variacao.nome %}
                                        {{ variacao.nome }}
                                    {% else  %}
                                        {{ variacao }}
                                    {% endif  %}
                                    </option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        {% endif %}
                    </div>

                <!-- Botões de Comprar ou Adicionar ao Carrinho -->
                <div class="content d-flex justify-content-start mb-5" style="width: 100%;">
                    <!-- <a href="{% url 'produto:comprar' %}">
                        <button class="btn btn-primary" type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
                                <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                            </svg>
                            Comprar</button> 
                    </a> -->
                    <button class="btn btn-outline-primary ml-2" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                        Adicionar ao Carrinho</button>
                </div>

                </form>


            </div>
        </div>
    </div>

    <div class="row" style="min-height: 100vh;">
        <div class="col"></div>
        <div class="col-8">
            <div class="mt-5 mb-5">
                <h2 class="text-center mt-5 mb-5">{{ produto.nome }}</h2>
                <p class="text-justify">
                    {{ produto.descricao_longa|linebreaks }}
                </p>
            </div>
        </div>
        <div class="col"></div>
    </div>

    <div class="row" style="min-height: 100vh;">
        <div class="col"></div>
        <div class="col-8">
            <div class="mt-5 mb-5">
                <h2 class="text-center mt-5 mb-5">Avaliações</h2>
                
                <div class="row mb-4">
                    <h4 class="mx-4">Deixe sua avaliação</h4>
                    <form action="{% url 'produto:comentar' %}" class="mx-4" method="POST">
                        {% csrf_token %}
                        <div class="row mx-auto mb-2">                           
                            <textarea class="ms-2" name="comentario" id="comentario" cols="105" rows="5" placeholder="Insira seu comentário ..."></textarea>
                        </div>
                        <div class="row">
                            <div class="col d-flex justify-content-end">
                                <button class="btn btn-primary" type="submit">Comentar</button>
                            </div>
                        </div>
                    </form>
                </div>
                {% for comentario in comentarios %}
                <div class="row mb-2">
                    <div class="col border mx-4" style="border-radius: 10px;">
                        <div class="row border-bottom py-2" style="background-color: rgba(128, 128, 128, 0.493);">
                            <div class="col py-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                                <span>{{comentario.usuario_comentario}}</span>
                            </div>
                            <div class="col py-2">
                                <div class="row d-flex justify-content-end">
                                    <span class="px-2">{{ comentario.data_comentario|naturalday|title }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row pt-1">
                            <div class="col">
                                <p class="text-justify">
                                    {{comentario.comentario}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
        <div class="col"></div>
    </div>

</div>



{% endblock %}

produto/templates/produto/resumo.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}


<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'perfil:atualizar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ usuario.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ usuario.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.idade }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.data_nascimento }}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cpf|formata_cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ usuario.email }}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.endereco }}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.numero }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.complemento }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.bairro }}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cidade }}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.estado }}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cep|formata_cep }}</dd>
        </dl>
    </div>
</div>


<div class="row">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'parciais/_carrinho.html' %}
    </div>
</div>

<div class="row">
    <div class="col">
        <p class="lead text-right" style="font-size: 30px;"><span class="font-weight-bold">Total do Carrinho:</span>
             {{carrinho|cart_totals|formata_preco}}</p>
    </div>
</div>

<div class="row">
    <div class="col"></div>
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'pedido:pagar' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>


{% endblock %}